# Generated by Django 3.1.1 on 2020-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_id', models.IntegerField()),
                ('percent', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'probability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField()),
                ('gas_state', models.CharField(max_length=50)),
                ('temp_state', models.CharField(max_length=50)),
                ('flame_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
