# Generated by Django 3.1.1 on 2020-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_probability_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_temp', models.IntegerField(blank=True, null=True)),
                ('sense_gas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensitivity',
                'managed': False,
            },
        ),
    ]
